name: Build Go App

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binaries
        run: |
          for arch in amd64 arm64; do
            GOOS=linux GOARCH=$arch go build -o bin/paycue-linux-$arch ./cmd/paycue
            GOOS=linux GOARCH=$arch go build -o bin/paycue-cli-linux-$arch ./cmd/paycue-cli
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
